Repository TsubakiBotPad/pad-cogs, pull requests merged in 2021-06, with the labels that each got.

#1150 Fix evolist getting server_priority
  padinfo/view/monster_list/static_monster_list.py
Labels: bug, idna, menu2

#1155 Make single quotes work for exact matching
  dadguide/find_monster.py
Labels: id3

#1153 Change notnaonly to allservers
  dadguide/find_monster.py
  padinfo/padinfo.py
Labels: idna

#1154 Fix --na setting
  dadguide/find_monster.py
Labels: idna

#1152 Move other dadguide enums into common
  dadguide/common/enums.py
  dadguide/models/enum_types.py
  dadguide/models/monster_model.py
  dadguide/monster_graph.py
  dadguide/token_mappings.py
  padinfo/common/emoji_map.py
  tests/dadguide/database_context_test.py
Labels: refactor

#1156 Revert "Move other dadguide enums into common"
  dadguide/common/enums.py
  dadguide/models/enum_types.py
  dadguide/models/monster_model.py
  dadguide/monster_graph.py
  dadguide/token_mappings.py
  padinfo/common/emoji_map.py
  tests/dadguide/database_context_test.py
Labels: refactor

#1161 Fix seriesscroll
  padinfo/view/series_scroll.py
Labels: bug, idna

#1162 series_priority -> server_priority
  padinfo/view/series_scroll.py
Labels: bug, idna

#1165 Fix ls and lss
  padinfo/menu/leader_skill.py
  padinfo/padinfo.py
  padinfo/view/leader_skill.py
  padinfo/view/leader_skill_single.py
Labels: bug, idna, menu2

#1166 r_query can be None
  padinfo/padinfo.py
Labels: bug, idna

#1168 Stop playing with ims directly in MonsterListMenu
  padinfo/menu/monster_list.py
  padinfo/view/monster_list/monster_list.py
Labels: menu2, refactor

#1170 Move all dadguide enum types to enum_types.py
  dadguide/common/__init__.py
  dadguide/common/enums.py
  dadguide/dadguide.py
  dadguide/database_context.py
  dadguide/find_monster_tokens.py
  dadguide/idtest_mixin.py
  dadguide/models/enum_types.py
  dadguide/models/monster_stats.py
  dadguide/monster_graph.py
  dadguide/monster_index.py
  dadguide/token_mappings.py
Labels: refactor

#1171 Remove unused Server enum
  dadguide/models/enum_types.py
Labels: refactor

#1176 Write nadiff
  padinfo/menu/menu_map.py
  padinfo/menu/na_diff.py
  padinfo/padinfo.py
  padinfo/view/id.py
Labels: idna, menu2, new command

#1178 Use flags & don't fail for jp-only cards
  padinfo/menu/na_diff.py
  padinfo/padinfo.py
Labels: idna, menu2

#1179 Pull out invalid_monster_message
  padinfo/padinfo.py
Labels: idna, refactor

#1180 Rename query to do_query in ViewStates
  padinfo/padinfo.py
  padinfo/reaction_list.py
  padinfo/view/awakening_list.py
  padinfo/view/evos.py
  padinfo/view/id.py
  padinfo/view/materials.py
  padinfo/view/monster_list/all_mats.py
  padinfo/view/monster_list/id_search.py
  padinfo/view/monster_list/static_monster_list.py
  padinfo/view/pantheon.py
  padinfo/view/series_scroll.py
  padinfo/view/transforminfo.py
Labels: menu2, refactor

#1181 Refactor MonsterListMenu to get child ims from ViewState
  padinfo/menu/monster_list.py
  padinfo/view/monster_list/monster_list.py
Labels: menu2, refactor

#1183 MVP version of ^nadiffs
  padinfo/menu/monster_list.py
  padinfo/menu/na_diff.py
  padinfo/padinfo.py
  padinfo/view/common.py
  padinfo/view/id.py
  padinfo/view/monster_list/monster_list.py
Labels: idna, menu2, new command

#1184 Fix nadiffs child message delete function
  padinfo/menu/id.py
  padinfo/menu/na_diff.py
  padinfo/view/id.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/simple_text.py
Labels: idna, menu2

#1186 Support --nadiff in any MonsterList query
  padinfo/menu/awakening_list.py
  padinfo/menu/id.py
  padinfo/menu/na_diff.py
  padinfo/padinfo.py
Labels: enhancement, idna, menu2

#1188 Fix nadiffs & ids
  padinfo/padinfo.py
Labels: bug, idna

#1190 Add tradeable modifier
  dadguide/monster_index.py
  dadguide/token_mappings.py
Labels: id3

#1206 Add "tradable" as alias of "tradeable"
  dadguide/token_mappings.py
Labels: id3

#1208 Use ChildMenuType, not ChildMenuSelector
  padinfo/info.json
  padinfo/menu/awakening_list.py
  padinfo/menu/id.py
  padinfo/menu/na_diff.py
  padinfo/padinfo.py
Labels: refactor

#1211 Update readme
  README.md
Labels: documentation

#1220 Fix typo in evosort docstring
  padinfo/padinfo.py
Labels: documentation

#1221 Fix evosort preference
  padinfo/menu/id.py
Labels: bug, menu2

#1224 Load exchange data later
  dadguide/dadguide.py
  dadguide/models/monster_model.py
  dadguide/monster_graph.py
Labels: graph

#1228 Refactor respond with left/right in IdMenu
  padinfo/menu/id.py
  padinfo/view/components/view_state_base_id.py
Labels: menu2, refactor

#1229 Remove unused imports
  padinfo/menu/id.py
Labels: refactor

#1233 Log graph issues to owners correctly
  dadguide/dadguide.py
Labels: graph, logging

#1234 [PDE] Save event loops as variables for easy deletion
  padevents/__init__.py
  padevents/padevents.py
Labels: refactor

#1243 Move leader_skill_header to common
  padinfo/view/common.py
  padinfo/view/id.py
  padinfo/view/transforminfo.py
Labels: bug, refactor

#1241 Refactor seriesscroll
  padinfo/menu/series_scroll.py
  padinfo/padinfo.py
  padinfo/view/series_scroll.py
Labels: refactor

#1252 Fix PDE Typo
  dungeoncog/dungeoncog.py
  padevents/padevents.py
Labels: padevents

#1259 Rename AEP set offset function
  padevents/padevents.py
Labels: bug, padevents

#1262 Add level 120 stats to buttoninfo
  dadguide/models/monster_stats.py
  padinfo/core/button_info.py
  padinfo/view/button_info.py
Labels: buttoninfo, enhancement

#1264 Update slb atk latent to 8%
  dadguide/models/monster_stats.py
Labels: buttoninfo
