Repository TsubakiBotPad/pad-cogs, pull requests merged in 2021-08, with the labels that each got.

#1352 Fix bugs with buttoninfo and stat calculation
  dbcog/models/monster_stats.py
  padinfo/core/button_info.py
Labels: buttoninfo

#1355 idtest refactor
  dbcog/dbcog.py
  dbcog/idtest_mixin.py
Labels: id3, refactor, tests

#1357 Fix whitespace issue in short_with_emoji header
  padinfo/view/common.py
  padinfo/view/components/monster/header.py
Labels: bug

#1367 add "box" as token for vdp
  dbcog/token_mappings.py
Labels: id3

#1370 Add GlobalAdmin cog requirements
  channelmirror/info.json
  crud/info.json
  dbcog/info.json
  padglobal/info.json
Labels: documentation

#1371 Add converters for Server and StarterGroup
  padevents/info.json
  padevents/padevents.py
Labels: tsutils, padevents

#1376 Updates to tsutils 5
  azurelane/azurelane.py
  azurelane/info.json
  channelmirror/channelmirror.py
  channelmirror/info.json
  crud/crud.py
  crud/info.json
  dbcog/dbcog.py
  dbcog/errors.py
  dbcog/find_monster.py
  dbcog/find_monster_tokens.py
  dbcog/idtest_mixin.py
  dbcog/info.json
  dbcog/models/monster_model.py
  dbcog/models/monster_stats.py
  dbcog/monster_index.py
  dungeoncog/view/dungeon.py
  dungeoncog/view/simple.py
  feedback/feedback.py
  monidlistener/monidlistener.py
  padboard/padboard.py
  padbuildimg/padbuildimg.py
  padbuilds/padbuilds.py
  padevents/padevents.py
  padglobal/padglobal.py
  padglobal/view/which.py
  padguidedb/padguidedb.py
  padinfo/common/emoji_map.py
  padinfo/common/external_links.py
  padinfo/core/padinfo_settings.py
  padinfo/menu/button_info.py
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/monster_list.py
  padinfo/menu/series_scroll.py
  padinfo/menu/transforminfo.py
  padinfo/padinfo.py
  padinfo/view/awakening_help.py
  padinfo/view/awakening_list.py
  padinfo/view/button_info.py
  padinfo/view/common.py
  padinfo/view/components/monster/image.py
  padinfo/view/evos.py
  padinfo/view/id.py
  padinfo/view/id_traceback.py
  padinfo/view/leader_skill.py
  padinfo/view/leader_skill_single.py
  padinfo/view/materials.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/monster_list/static_monster_list.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/series_scroll.py
  padinfo/view/simple_text.py
  padinfo/view/transforminfo.py
  padmonitor/padmonitor.py
  padsearch/padsearch.py
  pricecheck/pricecheck.py
  profile/profile.py
  schoolidol/schoolidol.py
Labels: refactor, tsutils

#1383 Add blackmetal modifier
  dbcog/monster_graph.py
  dbcog/monster_index.py
  dbcog/token_mappings.py
Labels: id3

#1385 Fix temp exchange logic
  dbcog/monster_graph.py
Labels: bug, id3

#1386 Add Server-based shopnow tokens
  dbcog/monster_graph.py
  dbcog/monster_index.py
  dbcog/token_mappings.py
Labels: enhancement, id3
