Repository TsubakiBotPad/pad-cogs, pull requests merged in 2021-09, with the labels that each got.

#1403 Add ref to idtest rm
  dbcog/idtest_mixin.py
Labels: id3, tests

#1402 Fix AEP set searchstr
  channelmirror/channelmirror.py
  padevents/padevents.py
Labels: bug, padevents

#1405 Add collab as a modifier to ghcollab
  dbcog/monster_index.py
Labels: id3

#1409 Use Async Iterators for the idtest suite
  dbcog/idtest_mixin.py
Labels: id3, performance

#1411 Fix inequalities in ^expcurve
  padinfo/padinfo.py
  padinfo/view/experience_curve.py
Labels: bug

#1412 Force show +0 stats if you can't feed plus to a card
  dbcog/models/monster_model.py
  dbcog/monster_graph.py
  padinfo/padinfo.py
  padinfo/view/id.py
  requirements.txt
Labels: menu2, id3

#1413 Add ID as alias for ^id
  padinfo/padinfo.py
Labels: id3

#1415 Force AEP and AED to not repeat
  dbcog/models/scheduled_event_model.py
  padevents/padevents.py
Labels: padevents

#1416 Add VEM modifier
  dbcog/models/monster_model.py
  dbcog/monster_graph.py
  dbcog/monster_index.py
  dbcog/token_mappings.py
Labels: id3

#1417 Fix padevents
  padevents/padevents.py
Labels: padevents

#1424 Clarify adpem reporting help text
  crowddata/mixins/vem.py
Labels: ui-ux

#1425 [adpem] Update toggleskipconfirm docstring
  crowddata/mixins/vem.py
Labels: ui-ux

#1426 [adpem] Fix multiple sends for opted-out users
  crowddata/mixins/vem.py
Labels: bug

#1428 Add support for coop/solo & 110/120 flags
  dbcog/models/monster_model.py
  dbcog/models/monster_stats.py
  padinfo/padinfo.py
  padinfo/view/id.py
Labels: id3

#1429 Show all previous AS cds for transform cards
  dbcog/monster_graph.py
  padinfo/padinfo.py
  padinfo/view/id.py
Labels: menu2, id3

#1431 Use gray up arrow for awakenings
  padinfo/view/id.py
Labels: id3

#1432 Refactor tfinfo/id to use a superclass
  padinfo/menu/transforminfo.py
  padinfo/padinfo.py
  padinfo/view/common.py
  padinfo/view/components/base_id_main_view.py
  padinfo/view/id.py
  padinfo/view/transforminfo.py
Labels: menu2, id3, refactor

#1433 Fix hidden emojis
  padinfo/menu/transforminfo.py
Labels: bug, menu2

#1434 Use downr instead of DOWN-POINTING RED TRIANGLE
  padinfo/menu/transforminfo.py
  padinfo/view/components/base_id_main_view.py
Labels: id3, ui-ux

#1435 Add a couple awakening modifiers
  dbcog/token_mappings.py
Labels: id3

#1437 Split/Grouped evos for results in ^ids
  padinfo/padinfo.py
  padinfo/view/monster_list/id_search.py
Labels: id3, tsutils, ui-ux

#1438 Fix NADiff
  padinfo/padinfo.py
Labels: bug, id3

#1439 Refactor buttoninfo a bit
  padinfo/core/button_info.py
Labels: refactor, buttoninfo

#1440 Show atk++ instead of atk+ for 120 buttons
  padinfo/core/button_info.py
  padinfo/view/button_info.py
Labels: buttoninfo

#1441 Refactor buttoninfo
  padinfo/core/button_info.py
  padinfo/view/button_info.py
Labels: refactor, buttoninfo

#1443 Show evo scroll in ^buttoninfo
  padinfo/menu/button_info.py
  padinfo/menu/components/evo_scroll_mixin.py
  padinfo/menu/id.py
  padinfo/padinfo.py
  padinfo/view/button_info.py
  padinfo/view/components/evo_scroll_mixin.py
  padinfo/view/components/view_state_base_id.py
  padinfo/view/evos.py
  padinfo/view/id.py
  padinfo/view/materials.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
Labels: buttoninfo

#1445 Create ^scroll to replace numberscroll pref
  padinfo/menu/menu_map.py
  padinfo/menu/monster_list.py
  padinfo/menu/scroll.py
  padinfo/menu/series_scroll.py
  padinfo/padinfo.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/monster_list/scroll.py
Labels: menu2, id3

#1448 Skip jp monsters when scrolling with --na
  padinfo/view/monster_list/scroll.py
Labels: menu2, id3

#1446 Remove evoscroll preference
  padinfo/padinfo.py
  padinfo/view/button_info.py
  padinfo/view/components/evo_scroll_mixin.py
  padinfo/view/components/view_state_base_id.py
  padinfo/view/evos.py
  padinfo/view/id.py
  padinfo/view/materials.py
  padinfo/view/pantheon.py
Labels: id3

#1451 Show left/right arrows for emoji in numberscroll
  padinfo/menu/monster_list.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/monster_list/scroll.py
Labels: menu2, id3

#1454 Add ^attr command
  dbcog/dbcog.py
  dbcog/token_mappings.py
Labels: new command

#1456 Add a couple monster attr aliases
  dbcog/dbcog.py
  dbcog/token_mappings.py
Labels: id3

#1462 Use new TSUtils functions for AdPEM
  crowddata/mixins/vem.py
Labels: tsutils

#1464 Use DAY_CHANGE instead of ROLLOVER
  crowddata/mixins/vem.py
Labels: tsutils
