Repository TsubakiBotPad/pad-cogs, pull requests merged in 2021-02, with the labels that each got.

#677 Add cc modifier & readd cloud/tape
  dadguide/token_mappings.py
Labels: id3

#688 Add regular modifier
  dadguide/monster_index.py
  dadguide/token_mappings.py
Labels: id3

#689 Fix Event Enum being added twice
  dadguide/token_mappings.py
Labels: bug, id3

#690 Make crud series add write to json correctly
  crud/crud.py
Labels: id3

#691 Make debugid1 look at correct index
  padglobal/padglobal.py
Labels: bug

#693 Fix error on reaction add to embedless message
  padinfo/padinfo.py
Labels: bug, menu-rewrite

#694 Fix pricecheck refactor
  dadguide/old_monster_index.py
  padbuildimg/padbuildimg.py
  padglobal/padglobal.py
  padinfo/padinfo.py
  pricecheck/pricecheck.py
Labels: bug, id3

#692 Fix debugid1
  padglobal/padglobal.py
Labels: bug

#702 Fix multi word token priority
  dadguide/monster_index.py
  padinfo/core/find_monster.py
Labels: bug, id3

#704 Add transform availiable killer latents
  dadguide/monster_graph.py
  padinfo/core/id.py
  padinfo/id_menu.py
  padinfo/view/id.py
  padinfo/view_state/id.py
Labels: bug

#712 Add better test case confirmation
  padinfo/padinfo.py
Labels: id3

#713 Change x emoji back to standard
  padinfo/ls_menu.py
Labels: menu-rewrite

#714 Update id1 warning message text
  dadguide/old_monster_index.py
Labels: id3

#719 Rename awoken type
  dadguide/token_mappings.py
Labels: id3

#722 Fix less-strong token being added as best near-match
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: bug, id3

#723 Add evo to all evo monsters
  dadguide/monster_index.py
Labels: id3

#724 Refactor evo type & stackable per pipeline update
  dadguide/models/evolution_model.py
  dadguide/models/monster_model.py
  dadguide/monster_graph.py
  dadguide/monster_index.py
  padinfo/id_menu.py
  padinfo/view/materials.py
Labels: id3

#728 Adjust score for prefix-matching mw tokens
  padinfo/core/find_monster.py
Labels: id3

#729 Bump discordmenu version
  padinfo/info.json
Labels: menu-rewrite

#730 Empty list rather than None when no friendcog
  padinfo/padinfo.py
Labels: menu-rewrite

#731 Fix suvo not adding properly in id3 index
  dadguide/monster_graph.py
Labels: bug, id3

#733 Calculate treename earlier
  dadguide/monster_index.py
  padinfo/core/find_monster.py
Labels: id3

#736 Show supertokens in idmeaning
  dadguide/monster_index.py
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: id3

#740 Don't edit input to token dict combiner
  dadguide/monster_index.py
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: bug, id3

#748 Refactor new menu view states to not re-query
  padinfo/core/id.py
  padinfo/id_menu.py
  padinfo/padinfo.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/materials.py
  padinfo/view_state/otherinfo.py
  padinfo/view_state/pantheon.py
  padinfo/view_state/pic.py
Labels: menu-rewrite

#747 Support override tree/nicknames fields in gdoc
  dadguide/dadguide.py
  dadguide/monster_index.py
Labels: id3

#752 Delete scrollmenu commands in prep for new menu
  padinfo/padinfo.py
Labels: menu-rewrite

#750 Convert Id views to using new menu code
  padinfo/emojiupdaters.py
  padinfo/id_menu.py
  padinfo/id_menu_old.py
  padinfo/padinfo.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/materials.py
  padinfo/view_state/otherinfo.py
  padinfo/view_state/pantheon.py
  padinfo/view_state/pic.py
Labels: menu-rewrite

#749 Fix return type for name token processor
  padinfo/core/find_monster.py
Labels: id3

#753 Fix ls menu & refactor get monster from ims
  padinfo/core/id.py
  padinfo/ls_menu.py
  padinfo/view_state/common.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/materials.py
  padinfo/view_state/otherinfo.py
  padinfo/view_state/pantheon.py
  padinfo/view_state/pic.py
Labels: menu-rewrite

#751 Create ^idtraceback
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: id3

#758 Fix ID
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: bug, id3

#756 Move idtest and its subcommands out of padinfo.py
  padinfo/idtest_mixin.py
  padinfo/padinfo.py
Labels: id3

#760 Perm gate idtest & print ref for failing tests
  padinfo/idtest_mixin.py
Labels: id3, tests

#762 Fix idtest handling of failing tests
  padinfo/idtest_mixin.py
Labels: id3, tests

#768 Add full names of killer awakening modifiers
  dadguide/token_mappings.py
Labels: enhancement, id3

#770 Add warning when user uses id1 syntax in an id3 query
  dadguide/token_mappings.py
  padinfo/padinfo.py
Labels: id3

#772 Fix indexes
  padinfo/padinfo.py
Labels: bug, id3

#771 Support adding modifiers via sheet
  dadguide/monster_index.py
  dadguide/token_mappings.py
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: id3

#773 Make monster IDs count as manual tokens
  dadguide/monster_index.py
Labels: id3

#777 Add helpful text to idhelp
  padinfo/padinfo.py
Labels: documentation, id3

#776 Allow a negated name token w/o additional name tokens
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: enhancement, id3

#775 Cutover all commands other than id1 itself to id3
  dadguide/old_monster_index.py
  padbuildimg/padbuildimg.py
  padglobal/padglobal.py
  padinfo/common/config.py
  padinfo/core/find_monster.py
  padinfo/core/leader_skills.py
  padinfo/core/transforminfo.py
  padinfo/id_menu.py
  padinfo/padinfo.py
  padinfo/view_state/common.py
  padinfo/view_state/leader_skill.py
  pricecheck/pricecheck.py
Labels: id3

#778 Change id url
  dadguide/old_monster_index.py
  padinfo/padinfo.py
Labels: id3

#779 Wrap documentation link in idset beta warning
  padinfo/padinfo.py
Labels: documentation, id3

#781 Force tree to be 2+ monsters for auto-treenaming
  dadguide/monster_index.py
Labels: id3

#767 Return None in transition func when pane is unsupported
  padinfo/core/find_monster.py
  padinfo/id_menu.py
  padinfo/info.json
  padinfo/padinfo.py
  padinfo/view_state/evos.py
  padinfo/view_state/materials.py
  padinfo/view_state/pantheon.py
Labels: menu-rewrite

#785 Support multi-word tokens in NameTokenAliases
  dadguide/monster_index.py
Labels: id3

#787 Make id menu emojis optional when panes don't apply
  padinfo/id_menu.py
  padinfo/padinfo.py
  padinfo/view_state/common.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/materials.py
  padinfo/view_state/otherinfo.py
  padinfo/view_state/pantheon.py
  padinfo/view_state/pic.py
Labels: menu-rewrite

#789 Refactor id new menu code
  padinfo/core/id.py
  padinfo/id_menu.py
  padinfo/id_menu_old.py
  padinfo/padinfo.py
  padinfo/view/components/base.py
  padinfo/view_state/base.py
  padinfo/view_state/base_id.py
  padinfo/view_state/common.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/leader_skill.py
  padinfo/view_state/materials.py
  padinfo/view_state/otherinfo.py
  padinfo/view_state/pantheon.py
  padinfo/view_state/pic.py
  padinfo/view_state/transforminfo.py
Labels: menu-rewrite

#791 Warn when numberscroll reaches nonexistent monster
  padinfo/id_menu.py
  padinfo/view_state/base_id.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/materials.py
  padinfo/view_state/pantheon.py
Labels: menu-rewrite

#792 Remove unused menu1 emojis from padinfo
  padinfo/padinfo.py
Labels: menu-rewrite

#793 Fix bugs in lssingle & evolist from refactoring
  padinfo/id_menu_old.py
  padinfo/padinfo.py
Labels: bug, menu-rewrite

#794 Replace hardcoded indices with IdMenuPanes
  padinfo/padinfo.py
Labels: menu-rewrite

#796 Create MonsterListMenu & use to update EvoList
  padinfo/MonsterListMenu.py
  padinfo/padinfo.py
  padinfo/view/monster_list.py
  padinfo/view_state/monster_list.py
Labels: menu-rewrite

#800 Fix id1
  padinfo/padinfo.py
Labels: id3

#799 Remove Index1 (Actually)
  dadguide/__init__.py
  dadguide/dadguide.py
  dadguide/old_monster_index.py
  padglobal/padglobal.py
  padinfo/core/find_monster.py
  padinfo/padinfo.py
  padsearch/padsearch.py
Labels: id3

#802 Fix inline for padglobal 'which' failure msg cos emoji
  padglobal/padglobal.py
Labels: bug

#803 Move LeaderSkillSingle to new menu
  padinfo/id_menu_old.py
  padinfo/ls_menu.py
  padinfo/lss_menu.py
  padinfo/padinfo.py
  padinfo/view/leader_skill.py
  padinfo/view/leader_skill_single.py
  padinfo/view_state/leader_skill_single.py
Labels: menu-rewrite

#804 Don't inspect the stack while recursing through name tokens
  dadguide/monster_index.py
Labels: id3

#806 Fix error in idtest runall when there are no modifiers
  padinfo/idtest_mixin.py
Labels: bug, id3, tests

#807 Fully remove all id1 related things
  dadguide/dadguide.py
  padglobal/padglobal.py
Labels: id3

#808 Make padinfo new menu reaction listener raw
  padinfo/padinfo.py
Labels: menu-rewrite

#811 Log invalid id3 queries
  padinfo/padinfo.py
Labels: id3

#812 Make get_priority_tuple "public" in find_monster
  padinfo/core/find_monster.py
Labels: id3

#797 Add MonsterList linked menus for evolist & idsearch
  padinfo/id_menu.py
  padinfo/info.json
  padinfo/monster_list_menu.py
  padinfo/padinfo.py
  padinfo/pane_names.py
  padinfo/reaction_list.py
  padinfo/view/components/monster/header.py
  padinfo/view/monster_list.py
  padinfo/view_state/id.py
  padinfo/view_state/monster_list.py
Labels: menu-rewrite

#815 Fix number of emojis after home button was deleted
  padinfo/monster_list_menu.py
Labels: menu-rewrite

#816 Fix custom deletion in IdMenu
  padinfo/id_menu.py
Labels: bug, menu-rewrite

#817 Show correct base killers for cards that transform multiple times
  dadguide/monster_graph.py
Labels: bug

#818 Fix serialization of is_child for id menu
  padinfo/view_state/id.py
Labels: bug, menu-rewrite

#819 Fix IDSearch
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: bug

#824 Show JW Distance in ^tracebackid
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: id3

#822 Make child message a fully-deletable embed
  padinfo/id_menu.py
  padinfo/message_menu.py
  padinfo/monster_list_menu.py
  padinfo/padinfo.py
  padinfo/view/evos.py
  padinfo/view/id.py
  padinfo/view/links.py
  padinfo/view/message.py
  padinfo/view/otherinfo.py
  padinfo/view/pic.py
  padinfo/view/transforminfo.py
  padinfo/view_state/base.py
  padinfo/view_state/base_id.py
  padinfo/view_state/common.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/materials.py
  padinfo/view_state/message.py
  padinfo/view_state/monster_list.py
  padinfo/view_state/pantheon.py
Labels: menu-rewrite

#825 Rename message -> simple text & make menu folder
  padinfo/menu/__init__.py
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/leader_skill_single.py
  padinfo/menu/monster_list.py
  padinfo/menu/pane_names.py
  padinfo/menu/simple_text.py
  padinfo/menu/transforminfo.py
  padinfo/padinfo.py
  padinfo/reaction_list.py
  padinfo/view/simple_text.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/materials.py
  padinfo/view_state/monster_list.py
  padinfo/view_state/otherinfo.py
  padinfo/view_state/pantheon.py
  padinfo/view_state/pic.py
  padinfo/view_state/simple_text.py
Labels: menu-rewrite

#827 Delete id_menu_old
  padinfo/id_menu_old.py
  padinfo/padinfo.py
Labels: menu-rewrite

#829 Closable embed menu & use it for IdTraceback
  padinfo/menu/closable_embed.py
  padinfo/padinfo.py
  padinfo/view/id_traceback.py
  padinfo/view_state/closable_embed.py
Labels: menu-rewrite

#832 use IdTracebackViewProps instead of kwargs
  padinfo/menu/closable_embed.py
  padinfo/padinfo.py
  padinfo/view/id_traceback.py
  padinfo/view_state/closable_embed.py
Labels: menu-rewrite

#833 Refactor reaction list
  padinfo/info.json
  padinfo/menu/closable_embed.py
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/leader_skill_single.py
  padinfo/menu/monster_list.py
  padinfo/menu/simple_text.py
  padinfo/menu/transforminfo.py
  padinfo/padinfo.py
Labels: menu-rewrite

#834 Combine view & view state files
  padinfo/menu/closable_embed.py
  padinfo/menu/common.py
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/leader_skill_single.py
  padinfo/menu/monster_list.py
  padinfo/menu/pane_names.py
  padinfo/menu/simple_text.py
  padinfo/menu/transforminfo.py
  padinfo/padinfo.py
  padinfo/reaction_list.py
  padinfo/view/closable_embed.py
  padinfo/view/common.py
  padinfo/view/components/base.py
  padinfo/view/components/view_state_base.py
  padinfo/view/components/view_state_base_id.py
  padinfo/view/evos.py
  padinfo/view/id.py
  padinfo/view/leader_skill.py
  padinfo/view/leader_skill_single.py
  padinfo/view/links.py
  padinfo/view/lookup.py
  padinfo/view/materials.py
  padinfo/view/monster_list.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/simple_text.py
  padinfo/view/transforminfo.py
  padinfo/view_state/__init__.py
  padinfo/view_state/evos.py
  padinfo/view_state/id.py
  padinfo/view_state/leader_skill.py
  padinfo/view_state/leader_skill_single.py
  padinfo/view_state/materials.py
  padinfo/view_state/monster_list.py
  padinfo/view_state/otherinfo.py
  padinfo/view_state/pantheon.py
  padinfo/view_state/pic.py
  padinfo/view_state/simple_text.py
  padinfo/view_state/transforminfo.py
Labels: menu-rewrite

#842 Change MonsterIndex2 to MonsterIndex
  dadguide/dadguide.py
  dadguide/monster_index.py
  padglobal/padglobal.py
  padinfo/core/find_monster.py
  padinfo/core/leader_skills.py
  padinfo/idtest_mixin.py
  padinfo/padinfo.py
Labels: id3

#844 Move child menu logic to MonsterListMenu class
  padinfo/menu/closable_embed.py
  padinfo/menu/common.py
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/leader_skill_single.py
  padinfo/menu/monster_list.py
  padinfo/menu/simple_text.py
  padinfo/menu/transforminfo.py
  padinfo/padinfo.py
  padinfo/view/simple_text.py
Labels: menu-rewrite

#845 Clean up & add TODO about full child-menu support
  padinfo/menu/monster_list.py
  padinfo/padinfo.py
Labels: menu-rewrite

#850 Make numerical name tokens require exact matching
  padinfo/core/find_monster.py
Labels: id3

#854 Refactor find_monster
  padinfo/core/find_monster.py
  padinfo/core/leader_skills.py
  padinfo/core/transforminfo.py
  padinfo/idtest_mixin.py
  padinfo/padinfo.py
  padinfo/view/common.py
Labels: id3

#855 Use find_monsters in idsearch
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: id3

#856 Remove print statements in find_monster_search
  padinfo/core/find_monster.py
Labels: id3

#853 Rewrite collab/seriesscroll with menu2
  padinfo/menu/closable_embed.py
  padinfo/menu/common.py
  padinfo/menu/monster_list.py
  padinfo/menu/series_scroll.py
  padinfo/padinfo.py
  padinfo/view/series_scroll.py
Labels: menu-rewrite

#860 Add problematic series token set to fix sonia etc
  dadguide/monster_index.py
  dadguide/token_mappings.py
Labels: id3

#868 Strip whitespace from sheet
  dadguide/monster_index.py
Labels: bug, id3

#869 Add NA prioritization within trees
  padinfo/core/find_monster.py
Labels: id3

#872 Show equips for base
  padinfo/core/find_monster.py
Labels: id3

#886 Cross attack modifiers
  dadguide/token_mappings.py
Labels: id3

#894 Fix auto-treetoken for trees with equips
  dadguide/monster_index.py
Labels: id3

#895 Fix monster index syntax that was crashing load
  dadguide/monster_index.py
Labels: bug, id3

#897 Add prev/next monster buttons to SeriesScroll
  padinfo/menu/common.py
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/leader_skill_single.py
  padinfo/menu/monster_list.py
  padinfo/menu/series_scroll.py
  padinfo/menu/simple_text.py
  padinfo/menu/transforminfo.py
  padinfo/padinfo.py
  padinfo/view/series_scroll.py
Labels: menu-rewrite

#898 Fix reaction list filter for incomplete menus
  padinfo/reaction_list.py
Labels: bug, menu-rewrite

#899 More reaction list cleanup / fixes
  padinfo/reaction_list.py
Labels: menu-rewrite

#902 Use find_monster to lookup bosses
  padglobal/padglobal.py
Labels: id3

#900 Refactor new menu test_reaction_add listener
  padinfo/menu/menu_maps.py
  padinfo/padinfo.py
Labels: menu-rewrite, refactor

#903 Add ims exceptions, refactor listener more
  padinfo/menu/errors.py
  padinfo/menu/menu_maps.py
  padinfo/padinfo.py
Labels: menu-rewrite, refactor
