Repository TsubakiBotPad/pad-cogs, pull requests merged in 2021-05, with the labels that each got.

#999 Improve modded awakening matching logic
  dadguide/find_monster_tokens.py
Labels: id3

#1002 Fix which awakenings count as SAs
  dadguide/find_monster.py
  dadguide/find_monster_tokens.py
Labels: id3

#1021 Use discord-menu view state as base class
  padinfo/view/components/base.py
  padinfo/view/components/view_state_base.py
  padinfo/view/components/view_state_base_id.py
Labels: menu2, refactor

#1058 Use built-in get_emoji method
  padinfo/common/emoji_map.py
Labels: refactor

#1059 Fix some imports & reformat code
  padinfo/common/emoji_map.py
Labels: refactor

#1061 Make padglobal append follow aliases
  padglobal/padglobal.py
Labels: padglobal

#1062 Use tsutils base for menu panes
  padinfo/info.json
  padinfo/menu/closable_embed.py
  padinfo/menu/common.py
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/leader_skill_single.py
  padinfo/menu/monster_list.py
  padinfo/menu/series_scroll.py
  padinfo/menu/simple_text.py
  padinfo/menu/transforminfo.py
Labels: menu2, refactor

#1060 Make which an embed and add padglobal dumpwhich
  padglobal/__init__.py
  padglobal/menu/closable_embed.py
  padglobal/menu/menu_map.py
  padglobal/padglobal.py
  padglobal/view/closable_embed.py
  padglobal/view/which.py
Labels: padglobal

#1067 Support multi-page scrolling in ^ids
  padinfo/menu/monster_list.py
  padinfo/padinfo.py
  padinfo/view/monster_list.py
Labels: menu2

#1076 Edit wording for addleaderguide
  padglobal/padglobal.py
Labels: bug, padglobal

#1080 Update UX for padglobal which
  padglobal/padglobal.py
  padglobal/view/which.py
Labels: padglobal

#1085 Reorganize padglobal command hierarchy
  padglobal/padglobal.py
Labels: padglobal

#1087 Update pwhich dump and list
  padglobal/padglobal.py
Labels: padglobal

#1091 Rename Balance to Balanced
  dadguide/models/enum_types.py
  dadguide/models/monster_model.py
  dadguide/token_mappings.py
  padbuildimg/padbuildimg.py
  padsearch/padsearch.py
Labels: id3

#1084 Include equip effects in ^buttoninfo
  dadguide/models/monster_stats.py
  padinfo/core/button_info.py
  padinfo/padinfo.py
Labels: padglobal

#1099 Support "generators" for monster lists
  padinfo/menu/menu_map.py
  padinfo/menu/monster_list.py
  padinfo/menu/series_scroll.py
  padinfo/padinfo.py
  padinfo/view/monster_list/__init__.py
  padinfo/view/monster_list/all_mats.py
  padinfo/view/monster_list/id_search.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/monster_list/static_monster_list.py
  padinfo/view/series_scroll.py
Labels: menu2

#1105 Improve `which` "uncontroversial" message
  padglobal/padglobal.py
Labels: padglobal

#1108 Warn of aliases when using padglobal delete
  padglobal/padglobal.py
Labels: padglobal

#1112 Add bindclear, rowclear as aliases
  dadguide/token_mappings.py
Labels: id3

#1134 "JP buffed" instead of "JP Buffed"
  padinfo/view/components/monster/header.py
Labels: idna

#1139 Fix typo
  dadguide/monster_graph.py
Labels: bug

#1146 Add ^idset server and --notnaonly setting
  dadguide/dadguide.py
  dadguide/find_monster.py
  padinfo/padinfo.py
Labels: idna

#1147 Add idset server docstring
  padinfo/padinfo.py
Labels: documentation, id3, idna

#1148 Fix left-right arrows in MonsterListMenu
  padinfo/menu/monster_list.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/monster_list/static_monster_list.py
Labels: bug, idna, menu2

#1149 Move AwokenSkills enum to common/enums.py
  dadguide/common/enums.py
  dadguide/find_monster_tokens.py
  dadguide/models/monster_stats.py
  dadguide/token_mappings.py
Labels: refactor
