Repository TsubakiBotPad/pad-cogs, pull requests merged in 2021-01, with the labels that each got.

#341 Fix id3 search for equips by number
  padinfo/padinfo.py
Labels: id3

#342 Add pantheon search to id3
  dadguide/dadguide.py
  dadguide/monster_index.py
  dadguide/token_mappings.py
  padinfo/padinfo.py
Labels: id3

#347 Create fir3
  dadguide/dadguide.py
  padglobal/padglobal.py
Labels: id3

#422 Remove helpid and alias idhelp to it
  padinfo/padinfo.py
Labels: id3

#423 Add gdoc nicknames ignore in id1
  dadguide/dadguide.py
Labels: id3

#426 Add en series names as prefixes
  dadguide/monster_index.py
Labels: id3

#421 Support negated prefixes in queries
  padinfo/find_monster.py
  padinfo/padinfo.py
Labels: id3

#430 Update failed query text for id & id3
  padinfo/padinfo.py
Labels: id3

#419 Add beginning-of-token name token matching
  padinfo/find_monster.py
  padinfo/padinfo.py
Labels: id3

#444 Fix reused key in MiscPrefixes enum
  dadguide/token_mappings.py
Labels: id3

#454 Fix cloud awo name token/prefix conflict
  dadguide/token_mappings.py
Labels: bug, id3

#458 Add exportprefixes
  dadguide/database_context.py
  dadguide/models/base_model.py
  dadguide/token_mappings.py
  padinfo/padinfo.py
Labels: id3

#459 Fix prefix in id3 query failure message
  padinfo/padinfo.py
Labels: id3

#460 Add betacount
  padinfo/padinfo.py
Labels: id3

#462 Store historic lookups for id3
  padinfo/padinfo.py
Labels: id3

#467 Improve failed query message for id3
  padinfo/padinfo.py
Labels: id3

#483 Fix suffixes by reversing tokens in place
  padinfo/find_monster.py
Labels: id3

#486 idtest import
  padinfo/padinfo.py
Labels: id3

#491 IDTest remove element by name
  padinfo/padinfo.py
Labels: id3

#501 Add series type to crud
  crud/crud.py
  dadguide/models/series_model.py
  dadguide/monster_graph.py
Labels: id3

#503 Rename default to regular as series_type
  crud/crud.py
Labels: id3

#509 Add series type priority in id3
  crud/crud.py
  dadguide/monster_graph.py
  padinfo/find_monster.py
  padinfo/padinfo.py
Labels: id3

#513 Prioritize not jp-only collabs
  padinfo/padinfo.py
Labels: id3

#514 Exact name match > modifier fuzzy match
  padinfo/find_monster.py
  padinfo/padinfo.py
Labels: id3

#515 Fix multi-word token processing
  padinfo/find_monster.py
Labels: id3

#516 Add series mod tokens when in names
  dadguide/monster_index.py
Labels: id3

#517 Prioritize event cards and regular cards equally
  padinfo/find_monster.py
  padinfo/padinfo.py
Labels: id3

#519 Move from difflib to Jaro Winkler
  dadguide/monster_index.py
  padinfo/find_monster.py
  padinfo/info.json
  padinfo/padinfo.py
  requirements.txt
Labels: id3

#527 Allow name tokens to be inferred by the index
  dadguide/monster_index.py
Labels: id3

#529 Prepare for nickname sheet column order switching
  dadguide/dadguide.py
  dadguide/monster_index.py
Labels: id3

#534 Increase prefix matching threshold
  padinfo/find_monster.py
Labels: id3

#535 Write debugiddist
  padinfo/find_monster.py
  padinfo/padinfo.py
Labels: id3

#536 Make debugiddist look nicer
  padinfo/padinfo.py
Labels: id3

#537 Add romaji subnames as name tokens
  dadguide/monster_index.py
  padinfo/padinfo.py
Labels: id3

#541 Stop printing sa questionmark when no SAs
  padinfo/view/id.py
Labels: menu-rewrite

#543 Move name token aliases to gdoc from hardcoded
  dadguide/monster_index.py
  dadguide/token_mappings.py
Labels: id3

#548 Fix reincarnated pulling up srevo monsters
  dadguide/monster_index.py
  dadguide/token_mappings.py
  padinfo/id_menu.py
Labels: id3

#550 Fix na and jp modifiers
  dadguide/monster_index.py
  dadguide/token_mappings.py
Labels: id3

#551 make idna/idjp use id3 (by user pref)
  padinfo/padinfo.py
Labels: id3

#554 Log misspelled modifiers
  padinfo/padinfo.py
Labels: id3

#568 Make prefix matching word-length independent
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: id3

#569 Add lowpriority as a series type
  crud/crud.py
  padinfo/core/find_monster.py
Labels: id3

#571 Create EvoMats embed via new syntax
  dadguide/monster_graph.py
  padinfo/id_menu.py
  padinfo/padinfo.py
  padinfo/view/materials.py
Labels: menu-rewrite

#576 Support normal priority treenames from gdoc
  dadguide/monster_index.py
Labels: id3

#573 Remove +0 stats from ^otherinfo
  padinfo/id_menu.py
  padinfo/view/links.py
  padinfo/view/otherinfo.py
Labels: menu-rewrite

#578 Create idmeaning and add series to exportmodifiers
  dadguide/database_context.py
  padinfo/padinfo.py
Labels: id3

#580 Idmeaning - clarify token meanings
  padinfo/padinfo.py
Labels: id3

#581 Fix delimiter in idmeaning
  padinfo/padinfo.py
Labels: id3

#582 Add idmeaning to idhelp docs
  padinfo/padinfo.py
Labels: documentation, id3

#586 Remove modifiers related to a name token
  dadguide/monster_index.py
  padinfo/padinfo.py
Labels: id3

#591 Remove idna1 and idjp1
  padinfo/padinfo.py
Labels: id3

#600 Write lssingle with new syntax
  padinfo/id_menu.py
  padinfo/view/leader_skill.py
Labels: menu-rewrite

#607 Fix equip important token passdown delimitation
  dadguide/monster_index.py
Labels: id3

#618 Do a second pass without mwtokens
  padinfo/core/find_monster.py
  padinfo/padinfo.py
Labels: id3

#622 Fix overwritten values in known_mods
  dadguide/monster_index.py
  dadguide/token_mappings.py
Labels: id3

#623 Refactor Index
  dadguide/monster_index.py
Labels: id3

#625 Propagate name tokens when consistency after commas
  dadguide/monster_index.py
Labels: id3

#628 add idtest name
  padinfo/padinfo.py
Labels: id3, tests

#629 Fix command name for idtest name run
  padinfo/padinfo.py
Labels: bug, id3

#639 Add import and addreason to idtest name/fluff
  padinfo/padinfo.py
Labels: id3

#642 Remove id2
  dadguide/old_monster_index.py
  padinfo/id_menu.py
  padinfo/padinfo.py
Labels: id3

#643 Fix id2 discontinuation message
  padinfo/padinfo.py
Labels: id3

#641 Store idtest lastaction
  padinfo/emojiupdaters.py
  padinfo/padinfo.py
Labels: id3

#648 idtest runall
  padinfo/padinfo.py
Labels: id3

#649 Split name and fluff
  padinfo/padinfo.py
Labels: id3

#651 Add story modifier
  dadguide/monster_graph.py
  dadguide/monster_index.py
  dadguide/token_mappings.py
  tests/dadguide/database_context_test.py
Labels: id3

#654 Fix idtest add
  padinfo/padinfo.py
Labels: bug, id3, tests

#655 Fixes for idtest add
  padinfo/padinfo.py
Labels: id3

#657 Make idtest run set lastaction
  padinfo/padinfo.py
Labels: id3, tests

#662 make idmeaning show name tokens
  dadguide/monster_index.py
  padinfo/padinfo.py
Labels: id3

#663 IDMeaning wait until ready DG is ready
  padinfo/padinfo.py
Labels: id3

#673 Gather async sheet loading
  dadguide/monster_index.py
Labels: id3
