Repository TsubakiBotPad/pad-cogs, pull requests merged in 2021-03, with the labels that each got.

#906 Use Emoji class instead of PaneNames
  padinfo/menu/common.py
  padinfo/menu/id.py
  padinfo/menu/monster_list.py
  padinfo/menu/series_scroll.py
Labels: menu-rewrite, refactor

#919 Fix idtest import
  dadguide/idtest_mixin.py
Labels: bug, id3, tests

#924 Make `idtest remove` say what was removed
  dadguide/idtest_mixin.py
Labels: id3, tests

#935 Add author as an auto-filled query parameter in ID feedback
  padinfo/padinfo.py
Labels: id3

#947 Add indexed evo modifiers
  dadguide/monster_index.py
Labels: id3

#948 Add Orb Skin and Animated modifiers
  dadguide/monster_index.py
  dadguide/token_mappings.py
Labels: id3

#955 Fix punctuation
  dadguide/models/active_skill_model.py
  dadguide/models/leader_skill_model.py
  dadguide/models/monster_model.py
  padinfo/view/id.py
Labels: bug
