Repository TsubakiBotPad/pad-cogs, pull requests merged in 2021-07, with the labels that each got.

#1267 Make enhancements to buttoninfo
  padinfo/core/button_info.py
Labels: buttoninfo

#1273 Change signature and docstring
  padevents/padevents.py
Labels: documentation, enhancement, padevents

#1286 Improve add UX of channelmirror
  channelmirror/channelmirror.py
Labels: ui-ux

#1296 Support fluff nickname tokens in gdoc
  dadguide/monster_index.py
Labels: id3

#1299 Remove cross-cog import from dungeoncog
  dungeoncog/processors.py
Labels: dungeoncog

#1301 Improve aep show display with status emoji
  padevents/padevents.py
Labels: padevents, ui-ux

#1318 Support legacy AEDs for include3p
  padevents/padevents.py
Labels: padevents

#1319 Actually support legacy AEDs for include 3p
  padevents/padevents.py
Labels: padevents

#1323 Use custom emojis for +0 & 1x ls
  padinfo/view/common.py
  padinfo/view/id.py
Labels: ui-ux

#1324 Support removal of channels for AEP
  padevents/padevents.py
Labels: padevents

#1329 Bring padinfo to tsutils 4.0
  padinfo/padinfo.py
Labels: tsutils

#1327 Stop using emoji cache early for menu reactions
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/leader_skill_single.py
  padinfo/menu/na_diff.py
  padinfo/padinfo.py
  padinfo/reaction_list.py
Labels: menu2

#1337 Remove now-unnecessary delete from awakening_list
  padinfo/menu/awakening_list.py
Labels: menu2

#1338 Order alt versions consistently
  dadguide/monster_graph.py
Labels: id3

#1340 Order alt versions consistently (try 2)
  dadguide/monster_graph.py
Labels: id3

#1348 Fix dungeon emoji reactions
  dungeoncog/menu/dungeon.py
Labels: bug, dungeoncog, menu2

#1351 Use cloudfront url from tsutils
  dbcog/dbcog.py
  padbuildimg/padbuildimg.py
  padglobal/padglobal.py
  padinfo/view/components/monster/image.py
Labels: tsutils
