Repository TsubakiBotPad/pad-cogs, pull requests merged in 2022-01, with the labels that each got.

#1555 Fix AdPEM issues
  crowddata/mixins/adpem/adpem.py
  crowddata/mixins/adpem/view/show_stats.py
Labels: adpem

#1556 Move ActiveSkillModel @properties to init
  dbcog/models/active_skill_model.py
Labels: refactor

#1557 Use number_emoji_small
  padinfo/view/components/base_id_main_view.py
  requirements.txt
Labels: tsutils, ui-ux

#1558 Use right hook arrow instead of right arrow
  padinfo/view/components/base_id_main_view.py
Labels: ui-ux

#1560 Change transform emoji again
  padinfo/view/components/base_id_main_view.py
Labels: ui-ux

#1561 Bold subskill cd
  padinfo/view/components/base_id_main_view.py
Labels: ui-ux

#1563 Allow group to be None
  padevents/autoevent_mixin.py
Labels: padevents

#1562 Add padglobal eventswap command
  padglobal/padglobal.py
Labels: padglobal

#1566 Default group to red
  padevents/autoevent_mixin.py
  padevents/padevents.py
Labels: padevents

#1567 Change 'defense' text to shield emoji
  padinfo/core/leader_skills.py
Labels: ui-ux

#1569 Fix ^pde active
  padevents/autoevent_mixin.py
  padevents/events.py
  padevents/padevents.py
Labels: bug, refactor, padevents

#1571 Allow less than max pulls
  crowddata/mixins/adpem/adpem.py
Labels: adpem

#1574 shield_amount emoji
  padinfo/core/leader_skills.py
Labels: ui-ux
