Repository TsubakiBotPad/pad-cogs, pull requests merged in 2022-12, with the labels that each got.

#1856 Display AS, LS, instead of full words
  padinfo/view/components/base_id_main_view.py
  padinfo/view/transforminfo.py
Labels: ui-ux, id-etc

#1863 Add comment about MonsterModel limit_mult property
  dbcog/models/monster_model.py
Labels: documentation, dbcog

#1867 Add media modifier to id
  dbcog/find_monster/token_mappings.py
  dbcog/monster_index.py
Labels: id3

#1869 Add latents to CRUD
  crud/crud.py
  crud/tables/__init__.py
  crud/tables/awoken_skills.py
  crud/tables/latent_skills.py
  crud/tables/series.py
Labels: crud

#1871 Fix aep set failure message
  padevents/autoevent_mixin.py
Labels: padevents

#1875 Updated and added new monster stats in buttoninfo
  padinfo/core/button_info.py
Labels: buttoninfo

#1876 Remove +0 section from otherinfo and add Lv1
  padinfo/view/otherinfo.py
Labels: id-etc

#1878 Update Durandalf eq buttoninfo multiplier
  padinfo/core/button_info.py
Labels: buttoninfo
