Repository TsubakiBotPad/pad-cogs, pull requests merged in 2022-05, with the labels that each got.

#1671 Fix dgid help text
  dungeoncog/dungeoncog.py
Labels: documentation

#1672 Choose transforms deterministically
  dbcog/monster_graph.py
  dbcog/monster_index.py
Labels: graph

#1674 Refactor ^tradeable command
  monidlistener/monidlistener.py
Labels: refactor, tsutils

#1675 Fix removing invalid flags that have args
  dbcog/find_monster.py
  dbcog/find_monster_tokens.py
Labels: bug, id3

#1677 Add groups to monsters
  crud/crud.py
  dbcog/find_monster.py
  dbcog/models/monster_model.py
  dbcog/monster_graph.py
  dbcog/monster_index.py
  dbcog/token_mappings.py
  padinfo/padinfo.py
Labels: dbcog

#1686 Rename PadGuideDB to PipelineUI
  README.md
  pipelineui/__init__.py
  pipelineui/info.json
  pipelineui/pipelineui.py
Labels: pdb

#1687 Update pad-cogs README
  README.md
Labels: documentation

#1688 [CRUD] Add better help messages
  crud/crud.py
Labels: crud

#1692 Add gfeshop modifier
  dbcog/monster_graph.py
  dbcog/monster_index.py
  dbcog/token_mappings.py
Labels: id3

#1699 Set ready flag per-index
  dbcog/dbcog.py
  dbcog/find_monster.py
  dbcog/idtest_mixin.py
  dbcog/monster_index.py
  padinfo/core/leader_skills.py
  padinfo/padinfo.py
Labels: id3, performance

#1704 Add selfhasmat
  dbcog/dbcog.py
  dbcog/find_monster/__init__.py
  dbcog/find_monster/find_monster.py
  dbcog/find_monster/find_monster_tokens.py
  dbcog/find_monster/idtest_mixin.py
  dbcog/find_monster/token_mappings.py
  dbcog/monster_graph.py
  dbcog/monster_index.py
  profile/profile.py
Labels: id3

#1706 Make debugiddist case insensitive
  padinfo/padinfo.py
Labels: id-etc
