Repository TsubakiBotPad/pad-cogs, pull requests merged in 2022-10, with the labels that each got.

#1826 Add `BGM` modifier & show by rarity
  dbcog/find_monster/token_mappings.py
  dbcog/monster_graph.py
  dbcog/monster_index.py
  padinfo/view/id.py
  padinfo/view/transforminfo.py
Labels: hacktoberfest-accepted, id3, graph, dbcog

#1827 Add BGM initializers to monster model
  api/responses/monster.py
  dbcog/models/monster_model.py
Labels: dbcog

#1831 Add SkillDisplay query setting
  padinfo/padinfo.py
  padinfo/view/components/base_id_main_view.py
  padinfo/view/id.py
  padinfo/view/transforminfo.py
Labels: id-etc

#1832 Update requirements.txt
  dbcog/find_monster/tokens/find_monster_tokens.py
  dbcog/info.json
  requirements.txt
Labels: hacktoberfest-accepted

#1834 Prettify GFE gem rush
  dbcog/models/dungeon_model.py
Labels: hacktoberfest-accepted
