Repository TsubakiBotPad/pad-cogs, pull requests merged in 2022-03, with the labels that each got.

#1611 compatibility update for tsutils 7.0.0
  crowddata/info.json
  crowddata/mixins/adpem/adpem.py
  crowddata/mixins/adpem/view/show_stats.py
  dbcog/dbcog.py
  padbuildimg/padbuildimg.py
  padglobal/padglobal.py
  padinfo/padinfo.py
  padinfo/view/awakening_help.py
  padinfo/view/button_info.py
  padinfo/view/common.py
  padinfo/view/components/base_id_main_view.py
  padinfo/view/components/evo_scroll_mixin.py
  padinfo/view/components/monster/__init__.py
  padinfo/view/components/monster/header.py
  padinfo/view/evos.py
  padinfo/view/experience_curve.py
  padinfo/view/id.py
  padinfo/view/id_traceback.py
  padinfo/view/leader_skill.py
  padinfo/view/leader_skill_single.py
  padinfo/view/links.py
  padinfo/view/lookup.py
  padinfo/view/materials.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/series_scroll.py
  padinfo/view/transforminfo.py
Labels: refactor, tsutils

#1614 Update TSUtils to 7.0.1
  crowddata/crowddata.py
  dbcog/find_monster.py
  dbcog/monster_graph.py
  padevents/autoevent_mixin.py
  padevents/events.py
  padinfo/core/button_info.py
  padinfo/menu/awakening_list.py
  padinfo/menu/button_info.py
  padinfo/menu/id.py
  padinfo/menu/leader_skill.py
  padinfo/menu/leader_skill_single.py
  padinfo/menu/monster_list.py
  padinfo/menu/na_diff.py
  padinfo/menu/scroll.py
  padinfo/menu/series_scroll.py
  padinfo/menu/transforminfo.py
  padinfo/padinfo.py
  padinfo/reaction_list.py
  padinfo/view/awakening_help.py
  padinfo/view/awakening_list.py
  padinfo/view/button_info.py
  padinfo/view/common.py
  padinfo/view/components/base_id_main_view.py
  padinfo/view/components/evo_scroll_mixin.py
  padinfo/view/components/view_state_base_id.py
  padinfo/view/evos.py
  padinfo/view/id.py
  padinfo/view/leader_skill.py
  padinfo/view/leader_skill_single.py
  padinfo/view/links.py
  padinfo/view/lookup.py
  padinfo/view/materials.py
  padinfo/view/monster_list/all_mats.py
  padinfo/view/monster_list/id_search.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/monster_list/scroll.py
  padinfo/view/monster_list/static_monster_list.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/series_scroll.py
  padinfo/view/transforminfo.py
Labels: tsutils

#1615 Record historic lookups after querying
  dbcog/dbcog.py
  dbcog/find_monster.py
  padinfo/padinfo.py
Labels: id3, performance

#1617 QuerySettings instead of Color in menus
  crowddata/mixins/adpem/adpem.py
  dungeoncog/dungeoncog.py
  dungeoncog/menu/dungeon.py
  dungeoncog/menu/simple.py
  dungeoncog/view/dungeon.py
  dungeoncog/view/simple.py
  padglobal/padglobal.py
  padglobal/view/which.py
  padinfo/padinfo.py
  padinfo/view/awakening_help.py
  padinfo/view/awakening_list.py
  padinfo/view/button_info.py
  padinfo/view/components/view_state_base_id.py
  padinfo/view/evos.py
  padinfo/view/experience_curve.py
  padinfo/view/id.py
  padinfo/view/id_traceback.py
  padinfo/view/leader_skill.py
  padinfo/view/leader_skill_single.py
  padinfo/view/links.py
  padinfo/view/lookup.py
  padinfo/view/materials.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/monster_list/scroll.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/series_scroll.py
  padinfo/view/transforminfo.py
Labels: menu2, refactor, tsutils

#1619 add color to showstats
  crowddata/mixins/adpem/view/show_stats.py
Labels: adpem

#1620 Fix leaderskill when no right query
  padinfo/padinfo.py
Labels: bug

#1622 Update for TSUtils 7.2
  crowddata/mixins/adpem/view/show_stats.py
  padglobal/view/which.py
  padinfo/padinfo.py
  padinfo/view/awakening_help.py
  padinfo/view/awakening_list.py
  padinfo/view/button_info.py
  padinfo/view/evos.py
  padinfo/view/experience_curve.py
  padinfo/view/id.py
  padinfo/view/id_traceback.py
  padinfo/view/leader_skill.py
  padinfo/view/leader_skill_single.py
  padinfo/view/links.py
  padinfo/view/lookup.py
  padinfo/view/materials.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/series_scroll.py
  padinfo/view/transforminfo.py
Labels: tsutils

#1626 Use MonsterHeader in dgcog
  dungeoncog/dungeon_monster.py
  dungeoncog/processors.py
  dungeoncog/view/dungeon.py
Labels: dungeoncog

#1627 Adjust dgid ui
  dungeoncog/view/dungeon.py
Labels: ui-ux, dungeoncog

#1628 Add subquery tokens
  dbcog/database_context.py
  dbcog/dbcog.py
  dbcog/find_monster.py
  dbcog/find_monster_tokens.py
  padinfo/padinfo.py
  padinfo/view/id_traceback.py
Labels: id3

#1630 Add hazmat as a hasmat alias
  dbcog/find_monster_tokens.py
Labels: id3, easter-egg

#1633 Add ^idset list contents
  padinfo/padinfo.py
Labels: id3

#1634 Fix order of cooldown text for transforms
  padinfo/view/components/base_id_main_view.py
Labels: bug, id-etc
