Repository TsubakiBotPad/pad-cogs, pull requests merged in 2022-07, with the labels that each got.

#1764 server isn't Optional[Server]
  dbcog/dungeon_context.py
  dungeoncog/dungeoncog.py
Labels: dungeoncog

#1771 Comment out uvloop in requirements
  requirements.txt
Labels: documentation

#1772 A couple README fixes
  README.md
Labels: documentation

#1775 Add () and restrict near-matching in subqueries
  dbcog/find_monster/find_monster.py
  dbcog/find_monster/tokens/find_monster_tokens.py
  padinfo/padinfo.py
Labels: id3

#1778 Add subheadings when there are subqueries in ^ids
  dbcog/dbcog.py
  dbcog/find_monster/extra_info.py
  dbcog/find_monster/find_monster.py
  padinfo/padinfo.py
  padinfo/view/monster_list/all_mats.py
  padinfo/view/monster_list/id_search.py
  padinfo/view/monster_list/monster_list.py
  padinfo/view/monster_list/scroll.py
Labels: id3, id-etc, dbcog

#1780 remove print
  padinfo/view/monster_list/monster_list.py
Labels: id-etc

#1792 grey latents+ 120s
  padbuildimg/assets/lat/abs120.png
  padbuildimg/assets/lat/att120.png
  padbuildimg/assets/lat/cltp.png
  padbuildimg/assets/lat/cltp120.png
  padbuildimg/assets/lat/dbl.png
  padbuildimg/assets/lat/ls120.png
  padbuildimg/assets/lat/nabs120.png
  padbuildimg/assets/lat/ncltp.png
  padbuildimg/assets/lat/ncltp120.png
  padbuildimg/assets/lat/ndbl.png
  padbuildimg/assets/lat/nsb++.png
  padbuildimg/assets/lat/nsb++120.png
  padbuildimg/assets/lat/nspn120.png
  padbuildimg/assets/lat/nunm120.png
  padbuildimg/assets/lat/sb++.png
  padbuildimg/assets/lat/sb++120.png
  padbuildimg/assets/lat/spn120.png
  padbuildimg/assets/lat/unm120.png
  padbuildimg/assets/lat/vdp120.png
Labels: pdchu

#1795 Add additional awakening nicknames
  dbcog/find_monster/token_mappings.py
Labels: id3

#1796 Add lock image to show for unused 7/8 slots
  padbuildimg/assets/lat/lock.png
Labels: pdchu

#1799 [pdchu] add new awakenings
  padbuildimg/assets/awk/100.png
  padbuildimg/assets/awk/101.png
  padbuildimg/assets/awk/102.png
  padbuildimg/assets/awk/103.png
  padbuildimg/assets/awk/104.png
  padbuildimg/assets/awk/82.png
  padbuildimg/assets/awk/83.png
  padbuildimg/assets/awk/84.png
  padbuildimg/assets/awk/85.png
  padbuildimg/assets/awk/86.png
  padbuildimg/assets/awk/87.png
  padbuildimg/assets/awk/89.png
  padbuildimg/assets/awk/90.png
  padbuildimg/assets/awk/91.png
  padbuildimg/assets/awk/92.png
  padbuildimg/assets/awk/93.png
  padbuildimg/assets/awk/94.png
  padbuildimg/assets/awk/95.png
  padbuildimg/assets/awk/96.png
  padbuildimg/assets/awk/97.png
  padbuildimg/assets/awk/98.png
  padbuildimg/assets/awk/99.png
Labels: pdchu

#1800 [pdchu] fix dbcog load
  padbuildimg/padbuildimg.py
Labels: bug, pdchu

#1801 type during refreshassets
  padbuildimg/padbuildimg.py
Labels: pdchu

#1802 2 unusable slots for 6 slot cards
  padbuildimg/assets/lat/none.png
Labels: pdchu

#1803 Rename none to unavailable
  padbuildimg/assets/lat/unavailable.png
Labels: pdchu

#1807 Change padevents LTD to Discord timestamp
  padevents/events.py
  padevents/padevents.py
Labels: padevents

#1808 Fix padevents output
  padevents/padevents.py
Labels: padevents

#1809 Remove groups from PDE
  dbcog/models/scheduled_event_model.py
  padevents/autoevent_mixin.py
  padevents/events.py
  padevents/padevents.py
Labels: padevents
