Repository TsubakiBotPad/pad-cogs, pull requests merged in 2022-04, with the labels that each got.

#1637 Don't cache monster ids
  dbcog/database_context.py
Labels: dbcog

#1638 Remove every last trace of id1 for real this time i swear
  dbcog/token_mappings.py
  padinfo/padinfo.py
Labels: id3

#1639 Add OrToken
  dbcog/dbcog.py
  dbcog/find_monster.py
  dbcog/find_monster_tokens.py
  dbcog/token_mappings.py
Labels: id3, tsutils

#1640 add gbr for guardbreak
  dbcog/token_mappings.py
Labels: id3

#1641 Add last query settings
  padinfo/view/awakening_help.py
  padinfo/view/experience_curve.py
Labels: id-etc

#1642 Awakening documentation
  dbcog/dbcog.py
  dbcog/token_mappings.py
  padinfo/padinfo.py
  padinfo/view/awakening_help.py
  padinfo/view/awakening_list.py
  padinfo/view/common.py
Labels: documentation, id3, tsutils, id-etc

#1644 Move exportmodifiers to dbcog
  dbcog/dbcog.py
  padinfo/padinfo.py
Labels: refactor

#1645 Use _do_idsetting & add ormod_prio setting
  dbcog/find_monster_tokens.py
  padinfo/padinfo.py
  padinfo/view/monster_list/id_search.py
Labels: id3, refactor

#1656 Stop saying "dadguide" in dbcog logging msgs
  dbcog/dbcog.py
Labels: dbcog

#1657 Display friendly error if dgid data is missing
  dungeoncog/dungeoncog.py
Labels: refactor, dungeoncog

#1660 Fix subqueries in id3
  dbcog/find_monster_tokens.py
Labels: id3

#1662 Change Some Token Types
  dbcog/monster_index.py
  dbcog/token_mappings.py
  padinfo/padinfo.py
Labels: id3
