Repository TsubakiBotPad/pad-cogs, pull requests merged in 2022-02, with the labels that each got.

#1584 Move MonsterImage to tsutils
  crowddata/mixins/adpem/view/show_stats.py
  padinfo/view/awakening_help.py
  padinfo/view/button_info.py
  padinfo/view/components/monster/image.py
  padinfo/view/evos.py
  padinfo/view/experience_curve.py
  padinfo/view/id.py
  padinfo/view/links.py
  padinfo/view/lookup.py
  padinfo/view/materials.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/transforminfo.py
Labels: refactor, tsutils, adpem

#1582 Coalesce repetitive events
  padevents/autoevent_mixin.py
  padevents/padevents.py
Labels: padevents

#1585 Use tsutils ClosableEmbedMenu for which
  crowddata/mixins/adpem/view/show_stats.py
  padglobal/menu/closable_embed.py
  padglobal/menu/menu_map.py
  padglobal/padglobal.py
  padglobal/view/closable_embed.py
Labels: menu2, refactor, tsutils, padglobal

#1590 Refactor the Monster Index
  dbcog/dbcog.py
  dbcog/monster_index.py
  padinfo/padinfo.py
Labels: id3, refactor

#1592 add note to readme about python 3.8
  README.md
Labels: documentation

#1594 Fix ^events
  padevents/events.py
  padevents/padevents.py
Labels: padevents

#1596 Add more dungeon boost names
  dbcog/token_mappings.py
Labels: id3

#1597 brick for this awakening
  dbcog/token_mappings.py
Labels: id3

#1599 Straight refactor to use tsutils MonsterLink class
  padinfo/common/external_links.py
  padinfo/view/awakening_help.py
  padinfo/view/button_info.py
  padinfo/view/components/evo_scroll_mixin.py
  padinfo/view/components/monster/header.py
  padinfo/view/evos.py
  padinfo/view/experience_curve.py
  padinfo/view/id.py
  padinfo/view/links.py
  padinfo/view/lookup.py
  padinfo/view/materials.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/transforminfo.py
Labels: refactor, tsutils

#1600 Use header_link instead of puzzledragonx
  padinfo/view/awakening_help.py
  padinfo/view/button_info.py
  padinfo/view/components/evo_scroll_mixin.py
  padinfo/view/components/monster/header.py
  padinfo/view/evos.py
  padinfo/view/experience_curve.py
  padinfo/view/id.py
  padinfo/view/links.py
  padinfo/view/lookup.py
  padinfo/view/materials.py
  padinfo/view/otherinfo.py
  padinfo/view/pantheon.py
  padinfo/view/pic.py
  padinfo/view/transforminfo.py
Labels: tsutils

#1602 Use send confirmation, cancellation message for idset
  padinfo/padinfo.py
Labels: ui-ux

#1604 Add padglobal prepend
  padglobal/padglobal.py
Labels: padglobal
